version: '3'

services:
  app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mongo:4.2.8
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: myroot
      MONGO_INITDB_DATABASE: api
